# Generated by Django 4.2.30 on 2026-09-17 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('UNIFORM', 'Uniform'), ('TRAVEL', 'Travel'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='agencies.agency')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
