# Generated by Django 4.2.30 on 2026-09-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shift_type', models.CharField(choices=[('STANDARD', 'Standard'), ('OVERTIME', 'Overtime'), ('NIGHT', 'Night'), ('BANK_HOLIDAY', 'Bank holiday')], default='STANDARD', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='agencies.site')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
