# Generated by Django 4.2.30 on 2026-09-17 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='licences', to=settings.AUTH_USER_MODEL),
        ),
    ]
