# Generated by Django 4.2.30 on 2026-09-17 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employment_type', models.CharField(choices=[('PAYE', 'PAYE'), ('SELF_EMPLOYED', 'Self-employed')], default='PAYE', max_length=20)),
                ('contact_notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('default_hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='agencies.agency')),
            ],
            options={
                'ordering': ['agency__name', 'name'],
            },
        ),
    ]
